runtime: python27
 api_version: 1
 threadsafe: true

 handlers:
 - url: /
   static_files: aarohantest/index.html
   upload: aarohantest/index.html

 - url: /(.*)
   static_files: aarohantest/\1
   upload: aarohantest/(.*)